# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBLRFnhPcv2ZuGzH3skcv3JEB6j-mx3w
"""

# Importing libraries
import pandas as pd

# Load dataset
df = pd.read_csv("/content/Crop_recommendation.csv")

# Display first 5 rows
df.head()

# Basic information about the dataset
df.info()

# Check for missing values
df.isnull().sum()

# Descriptive statistics
df.describe()

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Notebook içinde grafiklerin görünmesi için
# %matplotlib inline

plt.figure(figsize=(14,5))
sns.countplot(data=df, x='label', order=df['label'].value_counts().index)
plt.xticks(rotation=90)
plt.title("Crop Distribution")
plt.xlabel("Crop Type")
plt.ylabel("Count")
plt.show()

df.drop('label', axis=1).hist(figsize=(16,12), bins=20, color='skyblue', edgecolor='black')
plt.suptitle("Feature Distributions", fontsize=16)
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df.drop('label', axis=1).corr(), annot=True, cmap="YlGnBu", fmt=".2f")
plt.title("Feature Correlation Heatmap")
plt.show()

import warnings
warnings.filterwarnings("ignore")
sns.pairplot(df, hue='label', plot_kws={'alpha': 0.5}, height=1.8)
plt.suptitle("Pairwise Feature Distributions for All Crops", y=1.02)
plt.show()

from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import numpy as np

# Separate features and label
X = df.drop('label', axis=1)
y = df['label']

# Encode the labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Reshape input for LSTM: (samples, time steps, features)
X_reshaped = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))

print("X shape:", X_reshaped.shape)
print("y shape:", y_encoded.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # 0 = all logs, 2 = warnings only, 3 = errors only
# Get number of classes for output layer
num_classes = len(np.unique(y_encoded))

# Model architecture
model = Sequential()
model.add(LSTM(128, input_shape=(X_reshaped.shape[1], X_reshaped.shape[2]), return_sequences=False))
model.add(Dropout(0.3))
model.add(Dense(64, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))  # multi-class classification

# Compile the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Model summary
model.summary()

from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y_encoded, test_size=0.2, random_state=42)

# Early stopping to avoid overfitting
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

# Model training
history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

import matplotlib.pyplot as plt

# Accuracy graph
plt.figure(figsize=(10,5))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title("Model Accuracy Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()

# Loss graph
plt.figure(figsize=(10,5))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title("Model Loss Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import classification_report, confusion_matrix, f1_score
import seaborn as sns
import numpy as np

# Predict class probabilities
y_pred_probs = model.predict(X_test)

# Convert probabilities to class labels
y_pred = np.argmax(y_pred_probs, axis=1)

# Classification report
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# F1 Score
f1 = f1_score(y_test, y_pred, average='macro')
print("Macro F1 Score:", round(f1, 4))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(12,10))
sns.heatmap(cm, annot=False, fmt='d', cmap='YlGnBu',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)
plt.title("Confusion Matrix")
plt.xlabel("Predicted Crop")
plt.ylabel("Actual Crop")
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Pick a random test sample
idx = np.random.randint(0, X_test.shape[0])
sample = X_test[idx].reshape(1, 1, X_test.shape[2])
true_label = label_encoder.inverse_transform([y_test[idx]])[0]
pred_label = label_encoder.inverse_transform([np.argmax(model.predict(sample))])[0]

print(f"🌾 Actual Crop: {true_label}")
print(f"🤖 Predicted Crop: {pred_label}")

# Show input features (denormalized)
# Inverse scaling to get back original values
original_input = scaler.inverse_transform(X_test[idx].reshape(1, -1))[0]

columns = df.drop("label", axis=1).columns
for col, val in zip(columns, original_input):
    print(f"{col}: {val:.2f}")

model.save("crop_recommendation_lstm_model.h5")
print("✅ Model saved as crop_recommendation_lstm_model.h5")

df_new = df.drop(columns = "label")

sns.heatmap(df_new.corr(), annot=True, cmap="YlGnBu")
plt.show()

for column in df_new.columns.tolist():
    print(f"\nlabel with {column}\n")
    display(df.groupby("label")[column].describe().reset_index())

for column in df_new.columns.tolist():
    print(f"{column}: {df[column].skew()}")
    plt.figure(figsize = (8, 6), dpi = 100, facecolor = "white", edgecolor = "black")
    plt.boxplot(
        df[column],
        vert = True,
        patch_artist = True,
        boxprops=dict(facecolor="lightblue", color="blue"),
        medianprops=dict(color="red"),
        whiskerprops=dict(color="blue"),
        capprops=dict(color="blue")
    )
    plt.title("Box Plot of age before Outlier Handling", fontsize = 16, fontweight = "bold", color = "black")
    plt.ylabel(column)
    plt.grid(axis = "y", linestyle = "--", alpha = 0.7)
    plt.show()

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, cross_val_score

model = LogisticRegression()

# Define K-Fold
kf = KFold(n_splits=5, shuffle=True, random_state=42)
X = df.drop(columns = "label")
y = df["label"]

# Evaluate model with cross-validation
scores = cross_val_score(model, X, y, cv=kf, scoring="accuracy")

print("Cross-validation accuracies:", scores)
print("Mean Accuracy:", scores.mean())

print("Std Dev:", scores.std())

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y, shuffle = True)

model_train = LogisticRegression()

model_train.fit(x_train, y_train)

Y_pred = model_train.predict(x_test)

x=df.drop(["label"],axis=1)
y=df["label"]

from sklearn.preprocessing import StandardScaler
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100)
model.fit(x_train,y_train)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score

y_pred = model.predict(x_test)
y_pred_proba = model.predict_proba(x_test)

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='macro')
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')

roc_auc = roc_auc_score(y_test, y_pred_proba, multi_class='ovr', average='macro')
print(f"Accuracy: {accuracy}")
print(f"F1 Score: {f1}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"ROC AUC: {roc_auc}")

print("\nClassification Report:\n", classification_report(y_test, y_pred))

plt.scatter('N','label',data=df,c='blue') # Required Nitrogen Vs Crop
plt.title('N vs Crop')
plt.show()

plt.scatter('P','label',data=df,c='red') # Required Phosphorus Vs Crop
plt.title('P vs Crop')
plt.show()

plt.scatter('K','label',data=df,c='red') # Required Potesium Vs Crop
plt.title('K vs Crop')
plt.show()

plt.scatter('ph','label',data=df,c='red') # Required ph Vs Crop
plt.title('Ph vs Crop')
plt.show()

plt.scatter('rainfall','label',data=df,c='red') # Required rain Vs Crop
plt.title('Rain vs Crop')
plt.show()

df.shape

x_test.shape

x_train.shape